Docker container
KeithLev/Devops-Course-Starter pull request #6
Opened 2022-05-17 10:12 UTC by KeithLev

Please make sure you are raising this PR against your own repository and not the original. If it says https://github.com/CorndelWithSoftwire in the search bar right now, you are in the wrong place!

Please also don't forget to submit the PR's url to Aptem afterwards (by clicking on the corresponding exercise component, pasting the url in the textbox that appears and then pressing the finish button).

2022-05-19 13:48 UTC, hugh-emerson requested changes
Good work! Unfortunately, you're missing a COPY command that you need, but the fix should be straightforward. 

My other comments are just small suggestions

2022-05-19 13:48 UTC, hugh-emerson commented on Dockerfile
> +
Your image currently ONLY works when you run it with a bind mount. That's not what we want. At the very least, the production image needs to run without a bind mount - the production server should be able to download and run the image without worrying cloning this repository and mounting a folder.

So add a COPY command that copies your todo_app folder into the image, at least for the production stage.

2022-05-19 13:48 UTC, hugh-emerson commented on README.md
> +Run "docker compose" from the comand line
You mean `docker compose up`?

2022-05-19 13:48 UTC, hugh-emerson commented on Dockerfile
> +COPY ./poetry.toml ./pyproject.toml ./
You ought to copy in the poetry.lock file to make sure you use the exact same versions of all your dependencies

2022-05-19 13:48 UTC, hugh-emerson commented on docker-compose.yaml
> +      target: development
The service names dev/prod are the wrong way around compared to what they're actually targeting (production/development respectively)

2022-05-23 12:24 UTC, KeithLev commented on docker-compose.yaml
> +      target: development
*facepalm*

2022-05-23 12:26 UTC, merged